name: Update Framework Version Tag

on:
  push:
    branches:
    - master
jobs:
  tag-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
    - name: Bump and push version tag
      id: tag
      uses: broadinstitute/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
    - name: Notify environment repo of update
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: databiosphere/framework-env
        event-type: update-env
        client-payload: '{"env": "dev", "version": "${{ steps.tag.outputs.tag }}"}'
