name: Update Service Version Mapping

on:
  repository_dispatch:
    types: [version-bump]
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
    - name: Update service version map
      run: |
        jq '.["${{ github.event.client_payload.service }}"] = "${{ github.event.client_payload.version }}"' version.json > tmp.json
        mv tmp.json version.json
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Bump ${{ github.event.client_payload.service }} to ${{ github.event.client_payload.version }}" -a
        git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
    - name: Bump and push version tag
      id: tag
      uses: broadinstitute/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
    - name: Notify environment repo of update
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: databiosphere/framework-env
        event-type: update-env
        client-payload: '{"env": "dev", "version": "${{ steps.tag.outputs.tag }}"}'
