name: Update Service Version Mapping

on:
  repository_dispatch:
    types: [version-bump]
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Update service version map
      run: |
        jq '.["${{ github.event.client_payload.service }}"] = "${{ github.event.client_payload.version }}"' version.json > tmp.json
        mv tmp.json version.json
    - name: Commit files
      run: |
        git config --local user.email "gmalkov@broadinstitute.org"
        git config --local user.name "gmalkov"
        git commit -m "Bump ${{ github.event.client_payload.service }} to ${{ github.event.client_payload.version }}" -a
        git push "https://gmalkov:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
